# Generated by Django 3.1.4 on 2021-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210819_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/theblog/images/default_pic.jpg', upload_to='images/profile/'),
        ),
    ]
