# Generated by Django 3.1.4 on 2021-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210819_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/default_pic.jpg', upload_to='images/profile/'),
        ),
    ]
