# Generated by Django 3.1.4 on 2021-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210819_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to='images/profile/'),
        ),
    ]
